apiVersion: v1
kind: Service
metadata:
  name: daveboumanmessageservice
spec:
  type: LoadBalancer
  ports:
    - port: 3002
      targetPort: 3002
  selector:
    app: daveboumanmessageservice
